use crate::{
	builder::builder::Builder,
	model::{
		model::ExplicitModel,
		vas_model::{AbstractVas, VasPrismExport, VasTransition},
	},
};

/// Trait for Abstract VAS models to provide BMC-related functionality.
pub(crate) trait RagtimerRLBuilder: Builder {
	/// Returns the traces generated by the Ragtimer RL tool.
	fn rl_traces(&self) -> Vec<Vec<VasTransition>>;
}
//
// Example implementation for a concrete type that implements both Builder and AbstractVas.
// You must use a type that already implements Builder (since it's sealed).
// Suppose you have a struct like this:

pub struct VAS2Prism {
	// fields...
}

// Implement the Builder trait for VASBuilder.
impl Builder for VAS2Prism {
	type AbstractModelType = AbstractVas; 
	type ExplicitModelType = VasPrismExport; 

	type ResultType = (); // TODO: Replace `()` with your actual type

	fn is_abstracted(&self) -> bool {
		todo!()
	}

	fn creates_pmin(&self) -> bool {
		todo!()
	}

	fn creates_pmax(&self) -> bool {
		todo!()
	}

	fn finished(&mut self, result: &Self::ResultType) -> bool {
		todo!()
	}

	fn build(&mut self, explicit_model: &mut Self::ExplicitModelType) {
		todo!()
	}

	fn get_abstract_model(&self) -> std::sync::Arc<Self::AbstractModelType> {
		todo!()
	}
	// Provide required method implementations here.
	// For demonstration, you may leave them unimplemented!() or provide dummy implementations.
}

// Now implement RagtimerRLBuilder for VASBuilder.
impl RagtimerRLBuilder for VAS2Prism {
	fn rl_traces(&self) -> Vec<Vec<VasTransition>> {
		// Your implementation here.
		// For demonstration, return an empty Vec.
		Vec::new()
	}
}
